### PR TITLE
bcda-4207 Feature: auto set table bookkeeping columns

### PR DESCRIPTION
**Pull request by SMLuthi**
### Fixes [BCDA-4207](https://jira.cms.gov/browse/BCDA-4207)

Gorm used to handle the business logic for the `created_at` and `updated_at` columns in our database. Since Gorm has been removed these columns are not generating their values anymore.

### Change Details

Create a migration for updating the `created_at` columns to default to `now()` timestamp.
Create a migration for updating the `updated_at` columns to default to `now()` and to include a trigger that updates them to `now()` every time a row is updated.

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation

`created_at` and `updated_at` columns are now setting their values as intended.

### Feedback Requested

Check over my SQL and make sure im not doing any smells!

### CODE REVIEW

**Review by mtrang1263 — DISMISSED** [review]
LGTM!

**Comment by mtrang1263** [comment]
Something to think about moving forward. How do you think we can ensure we do not forget to add these triggers for any new tables that we introduce?

**Review by katyasoup — APPROVED** [review]
LGTM!

**Comment by SMLuthi** [comment]
@mtrang1263 by being great engineers! Jokes aside, maybe I could update the README in our migrations folder to make a note to add these columns in, what do you think?

**Comment by mtrang1263** [comment]
> @mtrang1263 by being great engineers! Jokes aside, maybe I could update the README in our migrations folder to make a note to add these columns in, what do you think?

Ah yes, great idea! We have the How-to section, maybe it can go there.

**Review by mtrang1263 — APPROVED** [review]
Thanks for updating the README!

**Review by mtrang1263 — APPROVED** [review]

**Pull request merged**
