### PR TITLE
BCDA-6892: Smoke test pipeline intermittent failures - add logging

### PR DESCRIPTION
**Pull request by laurenkrugen-navapbc**
## 🎫 Ticket

https://jira.cms.gov/browse/BCDA-6892

## 🛠 Changes

Added a logging statement to the function `validateRequests` to gain better visibility into intermittent failures during smoke tests.

## ℹ️ Context for reviewers

Our Integration/Smoke tests have been failing intermittently and we have been able to replicate the behavior manually. To gain additional visibility beyond the build console and in case the issue occurs in production, we should add a log statement to that function in the event of an error.

## ✅ Acceptance Validation

(How were the changes verified? Did you fully test the acceptance criteria in the ticket? Provide reproducible testing instructions and screenshots if applicable.)

## 🔒 Security Implications

- [ ] New data is stored or transmitted.
  

- [ ] This change introduces new software dependencies.
  

- [ ] This change impacts security controls or alters supporting software.
  

- [ ] A [security checklist](https://confluence.cms.gov/display/BCDA/Security+Checklists) is completed for this change.
  

- [ ] More team discussion required to evaluate security implications.

### CODE REVIEW

**Comment by kyeah** [comment]
Looks like we have an unrelated issue when resolving Go dependencies 😅 Not sure if it'll get resolved upstream at some point or we have to look into this more closely 🤔 Doesn't get resolved with a re-run.

```
panic: internal error: can't find reason for requirement on github.com/spf13/afero@v1.8.2
```

**Comment by laurenkrugen-navapbc** [comment]
@kyeah I attempted the fix we discussed this morning of removing the indirect dependencies and using `go mod tidy` -- I would like to review these changes very carefully since it updated more than the one that was breaking the CI build.

**Comment by laurenkrugen-navapbc** [comment]
@gsf helped get the issue fixed:

I had commented out the `usql` import in the `tools.go file`, but the dockerfile ignored the `//` character and downloaded it anyway. Once we removed the line altogether, it worked. `usql` has an issue in the latest version of `0.14.0` (which import `afero`, so removing the download of the latest version from `tools.go` fixed the problem.

**Comment by laurenkrugen-navapbc** [comment]
I will be abandoning this PR - the CI fix will be in its own PR and the go.mod and go.sum update will be removed and the original smoke test fix will also be put in its own PR.

**Pull request closed without merging**
