### PR TITLE
BCDA-4025: Remove HICNs from persistent storage

### PR DESCRIPTION
**Pull request by katyasoup**
### Fixes [BCDA-4025](https://jira.cms.gov/browse/BCDA-4025)

We no longer use HICNs for attribution or suppression; this ticket removes the stale data from our persistent storage (RDS). Related to: [https://jira.cms.gov/browse/BCDA-2381](https://jira.cms.gov/browse/BCDA-2381)

### Change Details
- Remove HICN field from `models.go#CCLFBeneficiary` and `models.go#Suppression`
- Remove references to HICN in `cclf.go`, `importer.go`,  and associated test files
- Create SQL migrations to remove HICN column from `cclf_beneficiaries` and `suppressions` tables; add migration tests

### Security Implications

- [ ] new software dependencies
- [ ] security controls or supporting software altered
- [ ] new data stored or transmitted
- [ ] security checklist is completed for this change
- [ ] requires more information or team discussion to evaluate security implications
- [ ] no PHI/PII is affected by this change

### Acceptance Validation
Unit tests updated and passing locally.
~Will deploy to dev and run smoke tests/migrations after review of proposed schema changes~
Deployed and smoke tested in dev

### Feedback Requested
Any missed steps or oversights and/or best practice guidance is appreciated

### CODE REVIEW

**Review by SMLuthi — DISMISSED** [review]
LGTM!

**Review by mtrang1263 — CHANGES_REQUESTED** [review]
Code changes look good!

Before we merge this PR, can we deploy to dev and run the final verification steps?
```
              1. Deploy feature branch to dev

               2. Run smoke tests

               3. Run sql migrate job to change the schema: https://bcda-ci.adhocteam.us/job/BCDA%20-%20SQL%20Migrate/

               4. Run smoke tests after schema has been changed.
```
```

**Comment by mtrang1263** [comment]
> Code changes look good!
> 
> Before we merge this PR, can we deploy to dev and run the final verification steps?
> 
> ```
>               1. Deploy feature branch to dev
> 
>                2. Run smoke tests
> 
>                3. Run sql migrate job to change the schema: https://bcda-ci.adhocteam.us/job/BCDA%20-%20SQL%20Migrate/
> 
>                4. Run smoke tests after schema has been changed.
> ```

Sorry, just saw in your AC that you're planning on doing it. I think you're good to roll it out and verify on dev!

**Comment by msnook** [comment]
@katyasoup @mtrang1263 
Will a DB migration be required as part of https://jira.cms.gov/browse/BCDA-4046

**Comment by mtrang1263** [comment]
Discussed offline, but we should add a new test to `./db/migrations/migrations_test.go` to verify that the schema can be applied and reverted.

**Review by mtrang1263 — APPROVED** [review]
LGTM!

**Comment by katyasoup** [comment]
> @katyasoup @mtrang1263
> Will a DB migration be required as part of https://jira.cms.gov/browse/BCDA-4046 ?
@msnook yes, just updated that ticket - let me know if you need any other info!

**Pull request merged**
