### PR TITLE
Updating golang version in docker base images

### PR DESCRIPTION
**Pull request by orenfromberg**
### Fixes [BCDA-2775](https://jira.cms.gov/browse/BCDA-2775)

This branch updates the golang base docker images to use the latest (1.14.1) version.

It also updates the version that Travis uses in CI.

### Proposed Changes

* Updating golang from 1.11.5 to 1.14.1

### Change Details

* Updated the golang alpine images to use the latest version available
* Updated debian stretch to buster where applicable
* Updating `Dockerfile.package` to use the alpine image instead of normal image

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

### Feedback Requested

* Does it make sense to use the full buster image for the tests?
* Does it make sense to use the alpine image for the package?

### CODE REVIEW

**Comment by orenfromberg** [comment]
Related to #177 #181

More info [here](https://jira.cms.gov/browse/BCDA-820).

**Comment by jeffcorpuz** [comment]
looks good to me!

**Comment by orenfromberg** [comment]
@jeffcorpuz possibly, I don't see any golang images tagged with `buster-slim` [here](https://hub.docker.com/_/golang?tab=tags) though.

**Comment by jeffcorpuz** [comment]
> @jeffcorpuz possibly, I don't see any golang images tagged with `buster-slim` [here](https://hub.docker.com/_/golang?tab=tags) though.

oh dang, looks like there isn't one after all, my bad. curious indeed.

**Pull request merged**
