### PR TITLE
DCGEO-211: updating CCLF parsing to work with the new TEST ACO

### PR DESCRIPTION
**Pull request by ericbuckley**
### Fixes [DCGEO-211](https://jira.cms.gov/browse/DCGEO-211)

Previously, we updated the ACO config to support a new [TEST ACO pattern](https://github.com/CMSgov/bcda-app/pull/726).  To fully test out that functionality, we will need the ability to create testing CCLF attribution files.  This PR introduces minor changes to the CCLF processing utilities to support the new ACO ID format. 

### Proposed Changes

- update CCLF file processing to support the `TEST\d{3}` ACO ID pattern

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### CODE REVIEW

**Review by KyRobbins — APPROVED** [review]

**Comment by Gabasol** [comment]
@ericbuckley - can you kindly add the BCDA devs to this PR to review? Thanks!

**Review by CosmicSyntax — APPROVED** [review]
🍺

**Review by SMLuthi — APPROVED** [review]
LGTM!

**Comment by Gabasol** [comment]
This looks good to merge I think @ericbuckley / @KyRobbins

**Pull request merged**
