### PR TITLE
Surface CCLF import error messages

### PR DESCRIPTION
**Pull request by kyeah**
## 🎫 Ticket

N/A

## 🛠 Changes

- Surface error messages that were not being printed/logged

## ℹ️ Context for reviewers

This would have helped us when debugging CCLF import failures.

## 🔒 Security Implications

- [ ] This PR adds a new software dependency or dependencies.
- [ ] This PR modifies or invalidates one or more of our security controls.
- [ ] This PR stores or transmits data that was not stored or transmitted before.
- [ ] This PR requires additional review of its security implications for other reasons.

### CODE REVIEW

**Comment by alex-dzeda** [comment]
This is good, I think there's an additional part that might want to add in the CCLF0/CCLF8 import in cclf.go, where if we're trying to import a CCLF file, but the file name != name from the metadata, we log the names of files that are present. This would bubble up directory issues, since file.name does not pass directory info as is.

**Comment by kyeah** [comment]
@alex-dzeda Thanks, that's a good callout. I did notice that all of the "unknown files" _should_ be printed earlier in the process through these logs:

```
Unknown file found: %s
```

However, those work based on regex string submatching and the check you mentioned in cclf.go require exact filename matching. It feels like those should match so we could update cclf.go to allow for substring matching?

**Comment by alex-dzeda** [comment]
> @alex-dzeda Thanks, that's a good callout. I did notice that all of the "unknown files" _should_ be printed earlier in the process through these logs:
> 
> ```
> Unknown file found: %s
> ```
> 
> However, those work based on regex string submatching and the check you mentioned in cclf.go require exact filename matching. It feels like those should match so we could update cclf.go to allow for substring matching?

Perfect, and switching to matching on the substring would also likely have led to KCF being unaffected by the changed structure.

**Comment by alex-dzeda** [comment]
Only other thing I can think of, too, is logging the permissions of the file (if that doesn't bubble up via your update in line 62), since that appears to be a likely culprit of these errors.

**Comment by kyeah** [comment]
@alex-dzeda I'm going to break out those separate updates into a ticket since they're a little more involved. The existing logging updates in this PR I think will help with the recurring unzipping issues, so I'd like to get those in today if possible 👋

**Review by alex-dzeda — APPROVED** [review]

**Comment by kyeah** [comment]
A hastily-made ticket, feel free to update 😄 

https://jira.cms.gov/browse/BCDA-7501

**Pull request merged**
