### PR TITLE
BCDA-1248 Documentation: Semantic links

### PR DESCRIPTION
**Pull request by dhgreene**
### Fixes [BCDA-1248](https://jira.cms.gov/browse/BCDA-1248)
This is a follow-on PR from #242 (BCDA-648), which updated the static site to document using client credentials with the `/auth/token` endpoint.  This PR includes edits suggested by our research team to clarify and increase accessibility.  

### Proposed changes:
- Use full URL's in text (avoid e.g. `/auth/token` in favor of `https://sandbox.bcda.cms.gov/auth/token`)
- Link to meaningful descriptions, not "find stuff **`here`**"

### Security Implications
No additional credentials or PII are exposed, and no additional functionality is documented.

### Acceptance Validation
Full link for tokens
Semantic link for getting token
Use your credentials link

### Feedback Requested
- Do the screenshots above accurately capture the intended changes?
- Are there additional changes that should be included?

### CODE REVIEW

**Comment by epfrankle** [comment]
Question on the "getting a token" link - where does that link go now? Is it to obtain credentials? Should that be a first step before "click the authorize button"?

**Comment by dhgreene** [comment]
> Question on the "getting a token" link - where does that link go now? Is it to obtain credentials? 

It goes to the section of the user guide that publishes the credentials.

> Should that be a first step before "click the authorize button"?

The very first step in the "Gathering the tools" section has the same link, asking them to have the credentials ready for a later step.  Either @knollfear or I felt it was important to link again here, at the point the credentials are actually used.  I'm happy to update it again to reduce awkwardness.

**Comment by knollfear** [comment]
> > Question on the "getting a token" link - where does that link go now? Is it to obtain credentials?
> 
> It goes to the section of the user guide that publishes the credentials.
> 
> > Should that be a first step before "click the authorize button"?
> 
> The very first step in the "Gathering the tools" section has the same link, asking them to have the credentials ready for a later step. Either @knollfear or I felt it was important to link again here, at the point the credentials are actually used. @epfrankle I'm happy to update it again to reduce awkwardness.

I know I have been adamantly opposed to opening internal (same domain) links in a new window, however, in this case we want people to pop out, grab something and come back.  I think that might justify opening it in a new window.

**Comment by dhgreene** [comment]
> . . . in this case we want people to pop out, grab something and come back. I think that might justify opening it in a new window.

@knollfear OK, anything that makes it better.  Done.

**Comment by epfrankle** [comment]
For the "use your credentials" link, another thought: what if we linked "use your credentials from the previous step" and finished the sentence with "to get an access token in this step" - unlinked. So:

[Use your credentials from the previous step](https://sandbox.bcda.cms.gov/user_guide.html#authentication-and-authorization) to get an access token in this step. 

Thoughts?

**Comment by dhgreene** [comment]
> [Use your credentials from the previous step](https://sandbox.bcda.cms.gov/user_guide.html#authentication-and-authorization) to get an access token in this step.

@epfrankle I like it better than I expected.  😸 That's now in the PR, and the screenshot above is updated.

**Pull request merged**
