### PR TITLE
BCDA-3870 - Adding smoke/postman tests for runouts

### PR DESCRIPTION
**Pull request by mtrang1263**
### Proposed Changes

We need to add additional tests to verify runout behaviors. In order to add these tests, we needed to update our approach with synthetic beneficiary data. Before, we would add new files under `./shared_files/cclf/files/synthetic`. We would duplicate new CCLF files for new ACOs (see https://github.com/CMSgov/bcda-app/pull/558).

Instead of duplicating and storing these CCLF files, this PR changes our synthetic CCLF ingest commands to copy the existing CCLF files and assign the ACO and fileType to the copied file. The data found in `./shared_files/cclf/files/synthetic` acts as a template.

### Change Details
1. Update `import-synthetic-cclf-package` command to accept a file type argument. This change allows us to ingest runout data.
2. Update `ImportCCLFPackage` to copy data from `./shared_files/cclf/files/synthetic` and assign the CMS_ID and file type dynamically.
3. Update smoke tests to request groupID/runout.
4. Update postman tests to request groupID/runout.
5. Add SQL script that was used to insert synthetic runout data for opensbx env.

**NOTE: ** We will need to make changes to our Jenkins smoke-test job to account for the data changes. That change can be found here: https://github.com/CMSgov/bcda-ops/pull/597

### Security Implications

- [ ] new software dependencies
- [ ] security controls or supporting software altered
- [x] data stored or transmitted was changed

We have removed redundant synthetic beneficiary data files.

- [ ] security checklist is completed for this change
- [ ] requires more information or team discussion to evaluate security implications

- [x] no PHI/PII is affected by this change

### Acceptance Validation
1. CI Passes.
2. Smoke tests successfully run on this branch. We were able to successfully [ingest data](https://bcda-ci.adhocteam.us/blue/organizations/jenkins/BCDA%20-%20Test%20-%20Integration%20Smoke/detail/BCDA%20-%20Test%20-%20Integration%20Smoke/2577/pipeline/103) using this new strategy.
3. Ran smoke tests successfully in all environments.

### CODE REVIEW

**Comment by mtrang1263** [comment]
Note on the failing test, BFD has not deployed the service-date changes to prod/prod-sbx. Once deployed, the failing smoke test should be resolved.

**Comment by mtrang1263** [comment]
Successfully ran smoke tests on dev environment with the new synthetic data strategy.

**Comment by msnook** [comment]
> Note on the failing test, BFD has not deployed the service-date changes to prod/prod-sbx. Once deployed, the failing smoke test should be resolved.

Will we hold onto this PR and only merge it after BFD has landed their changes?

**Review by msnook — APPROVED** [review]
✂️

**Comment by mtrang1263** [comment]
This PR is ready to review, but will wait on merging this until BFD deploys the latest release (which includes service-date filter) to production. See: https://cmsgov.slack.com/archives/CMT1YS2KY/p1605556528232600

**Comment by mtrang1263** [comment]
Successfully ran [smoke tests ](https://bcda-ci.adhocteam.us/job/BCDA%20-%20Test%20-%20Integration%20Smoke/2619/)with groupID runout on production.

**Review by SMLuthi — APPROVED** [review]
LGTM! Though I dont know all of the intricacies yet :P

**Pull request merged**
