### PR TITLE
PACA-371: Basic attribution file with MBIs

### PR DESCRIPTION
**Pull request by KyRobbins**
### Fixes [PACA-371](https://jira.cms.gov/browse/PACA-371)

The bcda test ACOs need to be assigned MBIs from the synthetic RDA data generated from synthea.

### Proposed Changes

The db migration script will add MBIs to various ACOs for testing purposes.

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### CODE REVIEW

**Review by ericbuckley — APPROVED** [review]

**Review by brianburton — APPROVED** [review]

**Review by katyasoup — COMMENTED** [review]
Looks good! Just missing `END $$; COMMIT;` at the end :)

**Comment by ericbuckley** [comment]
> Looks good! Just missing `END $$; COMMIT;` at the end :)

Ah, great catch.  Thanks @katyasoup

**Review by ericbuckley — APPROVED** [review]

**Review by brianburton — APPROVED** [review]

**Review by katyasoup — APPROVED** [review]
🎉

**Review by CosmicSyntax — APPROVED** [review]
🎉

**Pull request merged**
