### PR TITLE
Setup a cache directory to help improve linting performance

### PR DESCRIPTION
**Pull request by mtrang1263**
### Needed for [BCDA-4235](https://jira.cms.gov/browse/BCDA-4235)

While working on this [PR](https://github.com/CMSgov/bcda-app/pull/631), we discovered an increase in the amount of time we spend running `golangci-lint`. Using Google's FHIR dependency, increased the dependency tree (due to large number of files) which in turn increased the execution time of the linters.

Since we were running the golangci-lint in Docker container w/o keeping a persistent cache around, we have to re-run the entire lint stage from scratch everytime.

### Change Details
Update our `Makefile` to mount the result of `go env GOCACHE` as the cache directory for our linter.

By reusing the cache, we can skip over packages that already have been evaluated. This **does not** affect the accuracy of our linter.

This implementation was based off of this issue: https://github.com/golangci/golangci-lint/issues/1004

### Security Implications

- [ ] new software dependencies
- [ ] security controls or supporting software altered
- [ ] new data stored or transmitted
- [ ] security checklist is completed for this change
- [ ] requires more information or team discussion to evaluate security implications
- [ ] no PHI/PII is affected by this change

### Acceptance Validation
Validated on our Jenkins host that the linting times significantly improved.

**On main branch**

_Before_
```
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/CMSgov/bcda-app /go/src/github.com/CMSgov /go/src/github.com /go/src /go / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|exports_file|files|name|types_sizes|deps|imports) took 2m25.528503521s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 110.784945ms"
level=info msg="[linters context/goanalysis] analyzers took 4m16.56763684s with top 10 stages: buildir: 2m27.384890704s, fact_purity: 25.944191463s, fact_deprecated: 15.10477038s, printf: 14.79059892s, ctrlflow: 14.647345049s, inspect: 5.122003963s, SA1013: 935.526873ms, S1038: 901.009702ms, ineffassign: 771.669582ms, SA1012: 648.269948ms"
level=info msg="[linters context/goanalysis] analyzers took 14.965020121s with top 10 stages: buildir: 14.024411524s, U1000: 940.608597ms"
level=info msg="[runner] Issues before processing: 355, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): skip_files: 355/355, skip_dirs: 355/355, exclude-rules: 1/125, autogenerated_exclude: 355/355, identifier_marker: 355/355, exclude: 125/355, filename_unadjuster: 355/355, path_prettifier: 355/355, nolint: 0/1, cgo: 355/355"
level=info msg="[runner] processing took 26.804969ms with stages: identifier_marker: 11.845687ms, path_prettifier: 6.377095ms, autogenerated_exclude: 4.428267ms, exclude: 1.214575ms, skip_dirs: 1.016613ms, nolint: 968.361µs, exclude-rules: 650.432µs, cgo: 77.225µs, filename_unadjuster: 57.945µs, max_same_issues: 16.294µs, uniq_by_line: 16.194µs, max_from_linter: 15.922µs, diff: 15.762µs, skip_files: 15.408µs, severity-rules: 15.305µs, source_code: 15.083µs, max_per_file_from_linter: 14.987µs, path_prefixer: 14.741µs, sort_results: 14.557µs, path_shortener: 14.516µs"
level=info msg="[runner] linters took 43.445128003s with stages: goanalysis_metalinter: 39.429777755s, unused: 3.987589014s"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 1832 samples, avg is 154.1MB, max is 678.6MB"
level=info msg="Execution took 3m9.184386617s"
```
_After_
```
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/CMSgov/bcda-app /go/src/github.com/CMSgov /go/src/github.com /go/src /go / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (types_sizes|exports_file|files|imports|name|compiled_files|deps) took 23.359855409s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 38.210666ms"
level=info msg="[linters context/goanalysis] analyzers took 0s with no stages"
level=info msg="[linters context/goanalysis] analyzers took 0s with no stages"
level=info msg="[runner] Issues before processing: 355, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): nolint: 0/1, filename_unadjuster: 355/355, exclude-rules: 1/125, skip_dirs: 355/355, exclude: 125/355, skip_files: 355/355, autogenerated_exclude: 355/355, identifier_marker: 355/355, cgo: 355/355, path_prettifier: 355/355"
level=info msg="[runner] processing took 30.675599ms with stages: identifier_marker: 11.104277ms, path_prettifier: 6.035471ms, nolint: 5.92567ms, autogenerated_exclude: 4.627651ms, exclude: 1.149082ms, exclude-rules: 778.241µs, skip_dirs: 735.512µs, filename_unadjuster: 85.384µs, cgo: 83.405µs, max_same_issues: 14.789µs, severity-rules: 13.979µs, uniq_by_line: 13.938µs, max_from_linter: 13.916µs, max_per_file_from_linter: 13.68µs, diff: 13.579µs, sort_results: 13.573µs, path_shortener: 13.51µs, path_prefixer: 13.398µs, skip_files: 13.317µs, source_code: 13.227µs"
level=info msg="[runner] linters took 17.502101332s with stages: goanalysis_metalinter: 17.460711907s, unused: 9.443062ms"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 411 samples, avg is 71.8MB, max is 72.4MB"
level=info msg="Execution took 40.956609551s"
```

**On the Google FHIR branch**
_Before_
```
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/CMSgov/bcda-app /go/src/github.com/CMSgov /go/src/github.com /go/src /go / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (compiled_files|deps|exports_file|files|imports|types_sizes|name) took 3m32.318531077s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 115.351198ms"
level=info msg="[linters context/goanalysis] analyzers took 6m50.648855513s with top 10 stages: buildir: 4m41.700103213s, fact_deprecated: 45.06172986s, fact_purity: 25.608865938s, ctrlflow: 18.019671355s, printf: 16.902677133s, inspect: 9.449535747s, S1039: 352.286552ms, S1038: 326.841552ms, SA1006: 319.018224ms, ineffassign: 313.625322ms"
level=info msg="[linters context/goanalysis] analyzers took 13.49083229s with top 10 stages: buildir: 12.815895889s, U1000: 674.936401ms"
level=info msg="[runner] Issues before processing: 355, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): skip_files: 355/355, nolint: 0/1, path_prettifier: 355/355, skip_dirs: 355/355, autogenerated_exclude: 355/355, cgo: 355/355, filename_unadjuster: 355/355, identifier_marker: 355/355, exclude: 125/355, exclude-rules: 1/125"
level=info msg="[runner] processing took 33.745105ms with stages: path_prettifier: 12.758977ms, identifier_marker: 12.042824ms, autogenerated_exclude: 4.621303ms, exclude: 1.421365ms, skip_dirs: 1.021458ms, nolint: 877.803µs, exclude-rules: 676.118µs, cgo: 77.43µs, filename_unadjuster: 57.693µs, diff: 38.219µs, max_same_issues: 16.933µs, uniq_by_line: 15.641µs, skip_files: 15.26µs, max_per_file_from_linter: 15.258µs, severity-rules: 15.076µs, max_from_linter: 14.994µs, source_code: 14.878µs, sort_results: 14.813µs, path_shortener: 14.749µs, path_prefixer: 14.313µs"
level=info msg="[runner] linters took 1m15.96254341s with stages: goanalysis_metalinter: 1m12.405223314s, unused: 3.522626331s"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 2745 samples, avg is 243.9MB, max is 1482.4MB"
level=info msg="Execution took 4m48.538544151s"
```

_After
```
level=info msg="[config_reader] Config search paths: [./ /go/src/github.com/CMSgov/bcda-app /go/src/github.com/CMSgov /go/src/github.com /go/src /go / /root]"
level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
level=info msg="[loader] Go packages loading at mode 575 (name|types_sizes|compiled_files|deps|exports_file|files|imports) took 20.643457727s"
level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 38.722201ms"
level=info msg="[linters context/goanalysis] analyzers took 0s with no stages"
level=info msg="[linters context/goanalysis] analyzers took 0s with no stages"
level=info msg="[runner] Issues before processing: 355, after processing: 0"
level=info msg="[runner] Processors filtering stat (out/in): path_prettifier: 355/355, skip_dirs: 355/355, identifier_marker: 355/355, exclude-rules: 1/125, cgo: 355/355, filename_unadjuster: 355/355, nolint: 0/1, autogenerated_exclude: 355/355, exclude: 125/355, skip_files: 355/355"
level=info msg="[runner] processing took 36.383253ms with stages: identifier_marker: 22.465259ms, path_prettifier: 6.179173ms, autogenerated_exclude: 3.787725ms, exclude: 1.255168ms, nolint: 886.34µs, exclude-rules: 768.834µs, skip_dirs: 709.863µs, filename_unadjuster: 83.938µs, cgo: 82.412µs, max_same_issues: 17.132µs, max_from_linter: 15.822µs, source_code: 15.21µs, max_per_file_from_linter: 15.181µs, uniq_by_line: 15.067µs, sort_results: 14.969µs, path_prefixer: 14.808µs, severity-rules: 14.506µs, path_shortener: 14.433µs, diff: 14.174µs, skip_files: 13.239µs"
level=info msg="[runner] linters took 9.229259712s with stages: goanalysis_metalinter: 9.182046315s, unused: 9.858823ms"
level=info msg="File cache stats: 0 entries of total size 0B"
level=info msg="Memory: 302 samples, avg is 71.9MB, max is 73.0MB"
level=info msg="Execution took 30.042221119s"
```

### CODE REVIEW

**Review by CosmicSyntax — DISMISSED** [review]
Awesome! LGTM!

**Review by CosmicSyntax — APPROVED** [review]
LGTM

**Review by adamayd — APPROVED** [review]
LGTM!

**Review by SMLuthi — APPROVED** [review]
LGTM!

**Comment by davix** [comment]
Hi, should this be included in documentation https://github.com/golangci/golangci-lint/blob/master/docs/src/docs/usage/install/index.mdx, so that people won't suffer from slow docker run linting?

**Pull request merged**
